// Pociones apilables: se juntan por id, el uso gasta una unidad y la partida antigua se fusiona al cargar.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { World } from "../web/src/shared/world.js";
import { GameData } from "../web/src/shared/data.js";
import { Grid } from "../web/src/shared/grid.js";
import { isStack } from "../web/src/shared/items.js";
import { newInst } from "../web/src/shared/systems/itemsys.js";
import * as Inv from "../web/src/shared/inventory.js";
const J = f => JSON.parse(readFileSync(new URL("../web/data/" + f, import.meta.url)));
const npcDb = J("npc.json");
const grid = new Grid(40, 40, new Uint8Array(40 * 40 * 10));
let seed = 3; const rng = () => (seed = (seed * 16807) % 2147483647) / 2147483647;
const data = new GameData({ items: J("items.json"), magic: J("magic.json"), npcs: npcDb });
const w = new World({ grid, npcDb, data, spawns: [], rng, start: [10, 10] });
const red = data.named("RedPotion");
assert.ok(isStack(red), "la poción roja se apila");
assert.ok(!isStack(data.named("Dagger")));
const id = w.addPlayer("Beber", null, { gender: 1, stats: { str: 30, vit: 20, dex: 20, int: 10, mag: 10, chr: 10 } });
const p = w.ents.get(id);
const n0 = p.bag.filter(i => i.id === red.id).length;
Inv.addToBag(p, data, newInst(w, red.id, 4));
const pile = p.bag.filter(i => i.id === red.id);
assert.equal(pile.length, 1); assert.equal(n0, 1);
assert.equal(pile[0].count, 5);
p.hp = 1;
w.command(id, { t: "use", uid: pile[0].uid });
assert.equal(p.bag.find(i => i.id === red.id).count, 4, "usar gasta una unidad");
console.log("OK");
